In [1]:
# Initial imports
import os
from pathlib import Path
import pandas as pd
from newsapi import NewsApiClient
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
# Download/Update the VADER Lexicon
nltk.download('vader_lexicon')

# Initialize the VADER sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/zsar/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [3]:
!pwd

/Users/zsar/Desktop/Working_Folder

In [23]:
# Load ETH from CSV file
file_path = Path("Data_Ethereum2_EthTrader.csv")
eth_df = pd.read_csv(file_path, encoding="utf-8-sig", parse_dates=True, infer_datetime_format=True)
eth_df.head()

,Index,title,timestamp,date,Market
0,306,This is what peak human performance looks like,2021-08-02 04:02:39+00:00,2021-08-02,Bull
1,598,Mining is really bad for the environment,2021-08-01 09:26:18+00:00,2021-08-01,Bull
2,347,Welcome back boys. $2500 is here,2021-07-31 14:05:47+00:00,2021-07-31,Bull
3,700,*Crypto,2021-07-31 11:28:20+00:00,2021-07-31,Bull
4,726,easy to say,2021-07-31 08:49:31+00:00,2021-07-31,Bull

In [25]:
## Create the Ethereum sentiment scores DataFrame
Ethereum_sentiments = []

for title in eth_df:
    try:
        text = title
        #date = title["date"]
        sentiment = analyzer.polarity_scores(text)
        compound = sentiment["compound"]
        pos = sentiment["pos"]
        neu = sentiment["neu"]
        neg = sentiment["neg"]
        
        Ethereum_sentiments.append({
            
            
            "compound": compound,
            "positive": pos,
            "negative": neg,
            "neutral": neu,
            "text": text,
            #"date": date
            
        })
        
    except AttributeError:
        pass
    

eth_sentiment_df = pd.DataFrame(Ethereum_sentiments)

In [21]:
# Display Sentiment
eth_sentiment_df.head(10)

,compound,positive,negative,neutral,text
0,0.3612,0.263,0.000,0.737,This is what peak human performance looks like
1,-0.5849,0.000,0.387,0.613,Mining is really bad for the environment
2,0.4588,0.375,0.000,0.625,Welcome back boys. $2500 is here
3,0.0000,0.000,0.000,1.000,*Crypto
4,0.4404,0.592,0.000,0.408,easy to say
5,0.0000,0.000,0.000,1.000,Sold all my BTC and alts to go all in on ETH!
6,0.0772,0.085,0.000,0.915,"Probably because they want to buy it cheaper, ..."
7,-0.7430,0.000,0.612,0.388,FINALLY my broke ass has 1 ETH
8,0.0000,0.000,0.000,1.000,What did you think it was gonna do?
9,0.3666,0.091,0.124,0.785,I don't want lambos or luxury things. I just w...

In [8]:
# Describe the Ethereum Sentiment
eth_sentiment_df.describe()

         compound     positive     negative      neutral
count  1939.00000  1939.000000  1939.000000  1939.000000
mean      0.11033     0.113651     0.044247     0.842092
std       0.32038     0.183663     0.121859     0.208559
min      -0.93530     0.000000     0.000000     0.000000
25%       0.00000     0.000000     0.000000     0.727500
50%       0.00000     0.000000     0.000000     1.000000
75%       0.36035     0.200000     0.000000     1.000000
max       0.94930     1.000000     1.000000     1.000000